/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicPricingRouteRouteImport } from './routes/(public)/pricing/route'
import { Route as publicAuthRegisterRouteRouteImport } from './routes/(public)/_auth/register/route'
import { Route as publicAuthLoginRouteRouteImport } from './routes/(public)/_auth/login/route'

const publicPricingRouteRoute = publicPricingRouteRouteImport.update({
  id: '/(public)/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAuthRegisterRouteRoute = publicAuthRegisterRouteRouteImport.update({
  id: '/(public)/_auth/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAuthLoginRouteRoute = publicAuthLoginRouteRouteImport.update({
  id: '/(public)/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/pricing': typeof publicPricingRouteRoute
  '/login': typeof publicAuthLoginRouteRoute
  '/register': typeof publicAuthRegisterRouteRoute
}
export interface FileRoutesByTo {
  '/pricing': typeof publicPricingRouteRoute
  '/login': typeof publicAuthLoginRouteRoute
  '/register': typeof publicAuthRegisterRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)/pricing': typeof publicPricingRouteRoute
  '/(public)/_auth/login': typeof publicAuthLoginRouteRoute
  '/(public)/_auth/register': typeof publicAuthRegisterRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/pricing' | '/login' | '/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/pricing' | '/login' | '/register'
  id:
    | '__root__'
    | '/(public)/pricing'
    | '/(public)/_auth/login'
    | '/(public)/_auth/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicPricingRouteRoute: typeof publicPricingRouteRoute
  publicAuthLoginRouteRoute: typeof publicAuthLoginRouteRoute
  publicAuthRegisterRouteRoute: typeof publicAuthRegisterRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/pricing': {
      id: '/(public)/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof publicPricingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_auth/register': {
      id: '/(public)/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof publicAuthRegisterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_auth/login': {
      id: '/(public)/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicAuthLoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  publicPricingRouteRoute: publicPricingRouteRoute,
  publicAuthLoginRouteRoute: publicAuthLoginRouteRoute,
  publicAuthRegisterRouteRoute: publicAuthRegisterRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
