/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as authRegisterRouteRouteImport } from './routes/(auth)/register/route'
import { Route as authLoginRouteRouteImport } from './routes/(auth)/login/route'
import { Route as appWorkspaceRouteRouteImport } from './routes/(app)/workspace/route'

const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRouteRoute = authRegisterRouteRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRouteRoute = authLoginRouteRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appWorkspaceRouteRoute = appWorkspaceRouteRouteImport.update({
  id: '/(app)/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/workspace': typeof appWorkspaceRouteRoute
  '/login': typeof authLoginRouteRoute
  '/register': typeof authRegisterRouteRoute
  '/': typeof homeIndexRoute
}
export interface FileRoutesByTo {
  '/workspace': typeof appWorkspaceRouteRoute
  '/login': typeof authLoginRouteRoute
  '/register': typeof authRegisterRouteRoute
  '/': typeof homeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/workspace': typeof appWorkspaceRouteRoute
  '/(auth)/login': typeof authLoginRouteRoute
  '/(auth)/register': typeof authRegisterRouteRoute
  '/(home)/': typeof homeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/workspace' | '/login' | '/register' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/workspace' | '/login' | '/register' | '/'
  id:
    | '__root__'
    | '/(app)/workspace'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(home)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appWorkspaceRouteRoute: typeof appWorkspaceRouteRoute
  authLoginRouteRoute: typeof authLoginRouteRoute
  authRegisterRouteRoute: typeof authRegisterRouteRoute
  homeIndexRoute: typeof homeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/workspace': {
      id: '/(app)/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof appWorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  appWorkspaceRouteRoute: appWorkspaceRouteRoute,
  authLoginRouteRoute: authLoginRouteRoute,
  authRegisterRouteRoute: authRegisterRouteRoute,
  homeIndexRoute: homeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
