import {
  TRANSACTION_CATEGORY_LABELS,
  TRANSACTION_CATEGORY_TYPE,
} from '@/data/labels/transaction-category'
import {
  TRANSACTION_PAYMENT_METHOD_LABELS,
  TRANSACTION_PAYMENT_METHOD_TYPE,
} from '@/data/labels/transaction-payment-method'
import {
  TRANSACTION_TYPE,
  TRANSACTION_TYPE_LABELS,
} from '@/data/labels/transaction-type'
import { WORKSPACE_LABELS, WORKSPACE_TYPE } from '@/data/labels/workspace-type'

export const optionsTypeWorkspace = [
  { value: 'private', label: 'Privado' },
  { value: 'shared', label: 'Compartilhado' },
]

export const optionsTypeTransaction = [
  {
    value: TRANSACTION_TYPE.INCOME,
    label: TRANSACTION_TYPE_LABELS[TRANSACTION_TYPE.INCOME],
  },
  {
    value: TRANSACTION_TYPE.EXPENSE,
    label: TRANSACTION_TYPE_LABELS[TRANSACTION_TYPE.EXPENSE],
  },
  {
    value: TRANSACTION_TYPE.INVESTMENT,
    label: TRANSACTION_TYPE_LABELS[TRANSACTION_TYPE.INVESTMENT],
  },
]

export const optionsTransactionCategory = [
  {
    value: TRANSACTION_CATEGORY_TYPE.HOUSING,
    label: TRANSACTION_CATEGORY_LABELS[TRANSACTION_CATEGORY_TYPE.HOUSING],
  },
  {
    value: TRANSACTION_CATEGORY_TYPE.PERSONAL_CARE,
    label: TRANSACTION_CATEGORY_LABELS[TRANSACTION_CATEGORY_TYPE.PERSONAL_CARE],
  },
  {
    value: TRANSACTION_CATEGORY_TYPE.TRANSPORTATION,
    label:
      TRANSACTION_CATEGORY_LABELS[TRANSACTION_CATEGORY_TYPE.TRANSPORTATION],
  },
  {
    value: TRANSACTION_CATEGORY_TYPE.FOOD,
    label: TRANSACTION_CATEGORY_LABELS[TRANSACTION_CATEGORY_TYPE.FOOD],
  },
  {
    value: TRANSACTION_CATEGORY_TYPE.GROCERIES,
    label: TRANSACTION_CATEGORY_LABELS[TRANSACTION_CATEGORY_TYPE.GROCERIES],
  },
  {
    value: TRANSACTION_CATEGORY_TYPE.ENTERTAINMENT,
    label: TRANSACTION_CATEGORY_LABELS[TRANSACTION_CATEGORY_TYPE.ENTERTAINMENT],
  },
  {
    value: TRANSACTION_CATEGORY_TYPE.FAMILY,
    label: TRANSACTION_CATEGORY_LABELS[TRANSACTION_CATEGORY_TYPE.FAMILY],
  },
  {
    value: TRANSACTION_CATEGORY_TYPE.WORK,
    label: TRANSACTION_CATEGORY_LABELS[TRANSACTION_CATEGORY_TYPE.WORK],
  },
  {
    value: TRANSACTION_CATEGORY_TYPE.HEALTH,
    label: TRANSACTION_CATEGORY_LABELS[TRANSACTION_CATEGORY_TYPE.HEALTH],
  },
  {
    value: TRANSACTION_CATEGORY_TYPE.UTILITY,
    label: TRANSACTION_CATEGORY_LABELS[TRANSACTION_CATEGORY_TYPE.UTILITY],
  },
  {
    value: TRANSACTION_CATEGORY_TYPE.SALARY,
    label: TRANSACTION_CATEGORY_LABELS[TRANSACTION_CATEGORY_TYPE.SALARY],
  },
  {
    value: TRANSACTION_CATEGORY_TYPE.OTHER,
    label: TRANSACTION_CATEGORY_LABELS[TRANSACTION_CATEGORY_TYPE.OTHER],
  },
]

export const optionsTransactionPaymentMethod = [
  {
    value: TRANSACTION_PAYMENT_METHOD_TYPE.BANK_SLIP,
    label:
      TRANSACTION_PAYMENT_METHOD_LABELS[
        TRANSACTION_PAYMENT_METHOD_TYPE.BANK_SLIP
      ],
  },
  {
    value: TRANSACTION_PAYMENT_METHOD_TYPE.CREDIT_CARD,
    label:
      TRANSACTION_PAYMENT_METHOD_LABELS[
        TRANSACTION_PAYMENT_METHOD_TYPE.CREDIT_CARD
      ],
  },
  {
    value: TRANSACTION_PAYMENT_METHOD_TYPE.CASH,
    label:
      TRANSACTION_PAYMENT_METHOD_LABELS[TRANSACTION_PAYMENT_METHOD_TYPE.CASH],
  },
  {
    value: TRANSACTION_PAYMENT_METHOD_TYPE.DEBIT_CARD,
    label:
      TRANSACTION_PAYMENT_METHOD_LABELS[
        TRANSACTION_PAYMENT_METHOD_TYPE.DEBIT_CARD
      ],
  },
  {
    value: TRANSACTION_PAYMENT_METHOD_TYPE.OTHER,
    label:
      TRANSACTION_PAYMENT_METHOD_LABELS[TRANSACTION_PAYMENT_METHOD_TYPE.OTHER],
  },
  {
    value: TRANSACTION_PAYMENT_METHOD_TYPE.PIX,
    label:
      TRANSACTION_PAYMENT_METHOD_LABELS[TRANSACTION_PAYMENT_METHOD_TYPE.PIX],
  },
]

export const optionsWorkspaceType = [
  {
    value: WORKSPACE_TYPE.PRIVATE,
    label: WORKSPACE_LABELS[WORKSPACE_TYPE.PRIVATE],
  },
  {
    value: WORKSPACE_TYPE.SHARED,
    label: WORKSPACE_LABELS[WORKSPACE_TYPE.SHARED],
  },
]
